base_url = "https://kerisman.github.io/"
title = "kerisman.github.io"

theme = "no-style-please"

compile_sass = false
build_search_index = false

[markdown]
highlight_code = true

[extra]
#list_pages = true
no_list_date = true

header_nav = [
    { name = "About", url = "/about" },
    { name = "~home", url = "/" },
    { name = "#tags", url = "/tags" },
]

