base_url = "https://kerisman.github.io/"

theme = "no-style-please"

compile_sass = false
build_search_index = false

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Custom variables

